# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

target 'OverWatch-OW' do
    
    pod 'AFNetworking'
    pod 'MJExtension'
    #    pod 'MJRefresh'
    pod 'Masonry'
    pod 'BlocksKit'
    pod 'WMPageController'
    pod 'CocoaLumberjack'
    #    pod 'MBProgressHUD'
    pod 'TPKeyboardAvoiding'
    pod 'MLTransition'
    pod 'FMDB'
    pod 'CocoaAsyncSocket'
    pod 'RESideMenu'
    #    pod 'MWPhotoBrowser'
    pod 'FlatUIKit'
    pod 'YYKit'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'iCarousel'
    pod 'UITableView+FDTemplateLayoutCell'
    
end